SELECT * FROM online_retail WHERE CustomerID = 14911;
SELECT * FROM online_retail WHERE CustomerID = 12583;
SELECT * FROM online_retail WHERE CustomerID = 14688;
SELECT * FROM online_retail WHERE CustomerID = 17850;
SELECT * FROM online_retail WHERE INVOICENO = '536370';
SELECT * FROM online_retail WHERE INVOICENO = '536373';
SELECT * FROM online_retail WHERE INVOICENO = '536375';
SELECT * FROM online_retail WHERE INVOICENO = '536374';
SELECT * FROM online_retail WHERE INVOICENO = '636370';
SELECT * FROM online_retail WHERE STOCKCODE = '85123A';
SELECT * FROM online_retail WHERE STOCKCODE = '71053';
SELECT * FROM online_retail WHERE STOCKCODE = '84406B';
SELECT * FROM online_retail WHERE STOCKCODE = '84406G';
SELECT * FROM online_retail WHERE STOCKCODE = '84406E';
SELECT * FROM online_retail WHERE invoiceno='536365';
SELECT * FROM online_retail WHERE invoiceno='536366';
SELECT * FROM online_retail WHERE invoiceno='536367';
SELECT * FROM online_retail WHERE invoiceno='536368';
SELECT * FROM online_retail WHERE invoiceno='536369';
SELECT * FROM online_retail WHERE invoiceno='536370';
SELECT * FROM online_retail WHERE invoiceno='536371';
SELECT * FROM online_retail WHERE invoiceno='536372';
SELECT * FROM online_retail WHERE invoiceno='536373';
SELECT * FROM online_retail WHERE invoiceno='536374';
SELECT * FROM online_retail WHERE stockcode='85123A';
SELECT * FROM online_retail WHERE stockcode='71053';
SELECT * FROM online_retail WHERE stockcode='84406B';
SELECT * FROM online_retail WHERE stockcode='84406G';
SELECT * FROM online_retail WHERE stockcode='84406E';
SELECT * FROM online_retail WHERE stockcode='84029G';
SELECT * FROM online_retail WHERE stockcode='84029E';
SELECT * FROM online_retail WHERE stockcode='22752';
SELECT * FROM online_retail WHERE stockcode='21730';
SELECT * FROM online_retail WHERE stockcode='22633';
SELECT * FROM online_retail WHERE description='PARTY BUNTING';
SELECT * FROM online_retail WHERE description='JUMBO BAG RED RETROSPOT';
SELECT * FROM online_retail WHERE description='LUNCH BAG RED RETROSPOT';
SELECT * FROM online_retail WHERE description='WHITE HANGING HEART T-LIGHT HOLDER';
SELECT * FROM online_retail WHERE description='REGENCY CAKESTAND 3 TIER';
SELECT * FROM online_retail WHERE description='ASSORTED COLOUR BIRD ORNAMENT';
SELECT * FROM online_retail WHERE description='SET OF 3 CAKE TINS PANTRY DESIGN';
SELECT * FROM online_retail WHERE description='PACK OF 72 RETROSPOT CAKE CASES';
SELECT * FROM online_retail WHERE description='NATURAL SLATE HEART CHALKBOARD';
SELECT * FROM online_retail WHERE description='LUNCH BAG BLACK SKULL';
SELECT * FROM online_retail WHERE quantity=1;
SELECT * FROM online_retail WHERE quantity=2;
SELECT * FROM online_retail WHERE quantity=3;
SELECT * FROM online_retail WHERE quantity=4;
SELECT * FROM online_retail WHERE quantity=5;
SELECT * FROM online_retail WHERE quantity=6;
SELECT * FROM online_retail WHERE quantity=10;
SELECT * FROM online_retail WHERE quantity=12;
SELECT * FROM online_retail WHERE quantity=24;
SELECT * FROM online_retail WHERE quantity=48;

SELECT * FROM online_retail WHERE quantity > 50;
SELECT * FROM online_retail WHERE quantity > 100;
SELECT * FROM online_retail WHERE quantity > 200;
SELECT * FROM online_retail WHERE quantity < 0;
SELECT * FROM online_retail WHERE quantity BETWEEN 5 AND 20;
SELECT * FROM online_retail WHERE quantity BETWEEN 20 AND 50;
SELECT * FROM online_retail WHERE quantity >= 100;
SELECT * FROM online_retail WHERE quantity <= 2;
SELECT * FROM online_retail WHERE quantity <> 1;
SELECT * FROM online_retail WHERE quantity < 5;
SELECT * FROM online_retail WHERE unitprice=0.85;
SELECT * FROM online_retail WHERE unitprice=1.25;
SELECT * FROM online_retail WHERE unitprice=2.55;
SELECT * FROM online_retail WHERE unitprice=3.75;
SELECT * FROM online_retail WHERE unitprice=4.95;
SELECT * FROM online_retail WHERE unitprice > 5;
SELECT * FROM online_retail WHERE unitprice > 10;
SELECT * FROM online_retail WHERE unitprice > 20;
SELECT * FROM online_retail WHERE unitprice < 1;
SELECT * FROM online_retail WHERE unitprice BETWEEN 2 AND 8;
SELECT * FROM online_retail WHERE invoicedate='2010-12-01 08:26:00';
SELECT * FROM online_retail WHERE invoicedate='2010-12-01 08:28:00';
SELECT * FROM online_retail WHERE invoicedate >= '2011-01-01';
SELECT * FROM online_retail WHERE invoicedate >= '2011-03-01';
SELECT * FROM online_retail WHERE invoicedate >= '2011-06-01';
SELECT * FROM online_retail WHERE invoicedate < '2011-02-01';
SELECT * FROM online_retail WHERE invoicedate < '2011-07-01';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-01-01' AND '2011-01-31';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-02-01' AND '2011-03-31';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-06-01' AND '2011-12-01';
SELECT * FROM online_retail WHERE country='United Kingdom';
SELECT * FROM online_retail WHERE country='France';
SELECT * FROM online_retail WHERE country='Germany';
SELECT * FROM online_retail WHERE country='Netherlands';
SELECT * FROM online_retail WHERE country='Spain';
SELECT * FROM online_retail WHERE country='Belgium';
SELECT * FROM online_retail WHERE country='Switzerland';
SELECT * FROM online_retail WHERE country='Portugal';
SELECT * FROM online_retail WHERE country='Australia';
SELECT * FROM online_retail WHERE country='EIRE';
SELECT * FROM online_retail WHERE country='Norway';
SELECT * FROM online_retail WHERE country='Italy';
SELECT * FROM online_retail WHERE country='Sweden';
SELECT * FROM online_retail WHERE country='Japan';
SELECT * FROM online_retail WHERE country='Poland';
SELECT * FROM online_retail WHERE country='Austria';
SELECT * FROM online_retail WHERE country='Denmark';
SELECT * FROM online_retail WHERE country='Finland';
SELECT * FROM online_retail WHERE country='Singapore';
SELECT * FROM online_retail WHERE country='Channel Islands';

SELECT * FROM online_retail WHERE stockcode='84029G';
SELECT * FROM online_retail WHERE stockcode='84029E';
SELECT * FROM online_retail WHERE stockcode='22752';
SELECT * FROM online_retail WHERE stockcode='21730';
SELECT * FROM online_retail WHERE stockcode='22633';
SELECT * FROM online_retail WHERE description='PARTY BUNTING';
SELECT * FROM online_retail WHERE description='JUMBO BAG RED RETROSPOT';
SELECT * FROM online_retail WHERE description='LUNCH BAG RED RETROSPOT';
SELECT * FROM online_retail WHERE description='WHITE HANGING HEART T-LIGHT HOLDER';
SELECT * FROM online_retail WHERE description='REGENCY CAKESTAND 3 TIER';
SELECT * FROM online_retail WHERE description='ASSORTED COLOUR BIRD ORNAMENT';
SELECT * FROM online_retail WHERE description='SET OF 3 CAKE TINS PANTRY DESIGN';
SELECT * FROM online_retail WHERE description='PACK OF 72 RETROSPOT CAKE CASES';
SELECT * FROM online_retail WHERE description='NATURAL SLATE HEART CHALKBOARD';
SELECT * FROM online_retail WHERE description='LUNCH BAG BLACK SKULL';
SELECT * FROM online_retail WHERE quantity=1;
SELECT * FROM online_retail WHERE quantity=2;
SELECT * FROM online_retail WHERE quantity=3;
SELECT * FROM online_retail WHERE quantity=4;
SELECT * FROM online_retail WHERE quantity=5;
SELECT * FROM online_retail WHERE quantity=6;
SELECT * FROM online_retail WHERE quantity=10;
SELECT * FROM online_retail WHERE quantity=12;
SELECT * FROM online_retail WHERE quantity=24;
SELECT * FROM online_retail WHERE quantity=48;

SELECT * FROM online_retail WHERE quantity > 50;
SELECT * FROM online_retail WHERE quantity > 100;
SELECT * FROM online_retail WHERE quantity > 200;
SELECT * FROM online_retail WHERE quantity < 0;
SELECT * FROM online_retail WHERE quantity BETWEEN 5 AND 20;
SELECT * FROM online_retail WHERE quantity BETWEEN 20 AND 50;
SELECT * FROM online_retail WHERE quantity >= 100;
SELECT * FROM online_retail WHERE quantity <= 2;
SELECT * FROM online_retail WHERE quantity <> 1;
SELECT * FROM online_retail WHERE quantity < 5;
SELECT * FROM online_retail WHERE unitprice=0.85;
SELECT * FROM online_retail WHERE unitprice=1.25;
SELECT * FROM online_retail WHERE unitprice=2.55;
SELECT * FROM online_retail WHERE unitprice=3.75;
SELECT * FROM online_retail WHERE unitprice=4.95;
SELECT * FROM online_retail WHERE unitprice > 5;
SELECT * FROM online_retail WHERE unitprice > 10;
SELECT * FROM online_retail WHERE unitprice > 20;
SELECT * FROM online_retail WHERE unitprice < 1;
SELECT * FROM online_retail WHERE unitprice BETWEEN 2 AND 8;
SELECT * FROM online_retail WHERE invoicedate='2010-12-01 08:26:00';
SELECT * FROM online_retail WHERE invoicedate='2010-12-01 08:28:00';
SELECT * FROM online_retail WHERE invoicedate >= '2011-01-01';
SELECT * FROM online_retail WHERE invoicedate >= '2011-03-01';
SELECT * FROM online_retail WHERE invoicedate >= '2011-06-01';
SELECT * FROM online_retail WHERE invoicedate < '2011-02-01';
SELECT * FROM online_retail WHERE invoicedate < '2011-07-01';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-01-01' AND '2011-01-31';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-02-01' AND '2011-03-31';
SELECT * FROM online_retail WHERE invoicedate BETWEEN '2011-06-01' AND '2011-12-01';
SELECT * FROM online_retail WHERE country='United Kingdom';
SELECT * FROM online_retail WHERE country='France';
SELECT * FROM online_retail WHERE country='Germany';
SELECT * FROM online_retail WHERE country='Netherlands';
SELECT * FROM online_retail WHERE country='Spain';
SELECT * FROM online_retail WHERE country='Belgium';
SELECT * FROM online_retail WHERE country='Switzerland';
SELECT * FROM online_retail WHERE country='Portugal';
SELECT * FROM online_retail WHERE country='Australia';
SELECT * FROM online_retail WHERE country='EIRE';
SELECT * FROM online_retail WHERE country='Norway';
SELECT * FROM online_retail WHERE country='Italy';
SELECT * FROM online_retail WHERE country='Sweden';
SELECT * FROM online_retail WHERE country='Japan';
SELECT * FROM online_retail WHERE country='Poland';
SELECT * FROM online_retail WHERE country='Austria';
SELECT * FROM online_retail WHERE country='Denmark';
SELECT * FROM online_retail WHERE country='Finland';
SELECT * FROM online_retail WHERE country='Singapore';
SELECT * FROM online_retail WHERE country='Channel Islands';